-- Users table
DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`id_user` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(200) DEFAULT NULL,
	`email` VARCHAR(200) NOT NULL,
	`password` VARCHAR(200) NOT NULL,
	`slug` VARCHAR(200) DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME,
	PRIMARY KEY (`id_user`)
) ENGINE=InnoDB;